project:
  type: website
  output-dir: _site

website:
  title: "Canadian Metaresearch Data Challenge"
  sidebar:
    style: docked
    search: false
    contents:
      - href: index.qmd
        text: Overview
      - href: proposal.qmd
        text: Proposal
      - href: pipeline.qmd
        text: Data Sources, Model, and Pipeline

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: false
    grid:
      body-width: 1000px
      margin-width: 350px
    include-in-header:
      - text: |
          <style type="text/css">
          h1.hide {
            display: none;
          }
          </style>
  # pdf:
  #   documentclass: article
  #   geometry: margin=1in
  #   fontsize: 11pt
  #   toc: false