project:
  type: website
  output-dir: _site

bibliography: assets/CMDC.bib
csl: assets/chicago-author-date.csl
website:
  title: "Canadian Metaresearch Data Challenge"
  sidebar:
    style: docked
    search: false
    contents:
      - href: index.qmd
        text: Overview
      - href: proposal.qmd
        text: Proposal
      - href: pipeline.qmd
        text: Data Sources, Model, and Pipeline

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: false
    grid:
      body-width: 1100px
      margin-width: 200px
    include-in-header:
      - text: |
          <style type="text/css">
          h1.hide {
            display: none;
          }
          #quarto-document-content {
              text-align: justify;
            }
            .abstract {
              text-align: justify;
            }
          </style>